export const FETCH_SERVERS_INFO_START = 'FETCH_SERVERS_INFO_START';
export const FETCH_SERVERS_INFO_SUCCESS = 'FETCH_SERVERS_INFO_SUCCESS';
export const FETCH_SERVERS_INFO_FAIL = 'FETCH_SERVERS_INFO_FAIL';
